description: Identifies protein protein interaction from sequences
long_description: This method utilizes monomeric protein structure predictions to identify protein-protein interactions and models their structures.
homepage_url: https://github.com/guerler/springsuite/tools/springsuite/
name: springsuite
owner: guerler
type: unrestricted
categories:
 - Sequence Analysis
auto_tool_repositories:
  name_template: "{{ tool_id }}"
  description_template: "SpringSuite: {{ tool_name }}."
suite:
  name: "suite_springsuite"
  description: "A suite of tools designed for the identification and structural modeling of protein-protein interactions"
  type: repository_suite_definition
