categories:
- Sequence Analysis
description: converts bedGraph (wig) files into binary bigwig
homepage_url: https://genome.ucsc.edu/goldenPath/help/bigWig.html
long_description: UCSC wigtobigwig tool wrapper to make bigwig files for JBrowse or other browser tracks from very dense feature tracks. MIT licence.
name: wigtobigWig
owner: iuc
remote_repository_url: https://github.com/galaxyproject/tools-iuc/tree/master/tools/wigtobigwig
type: unrestricted
