categories:
- Data Managers
description: Install lineages databases for compleasm tool
long_description: |
  This datamanager downloads the lines available for Compleasm.
name: data_manager_compleasm
owner: iuc
remote_repository_url: https://github.com/galaxyproject/tools-iuc/tree/master/data_managers/data_manager_compleasm
type: unrestricted
homepage_url: https://github.com/huangnengCSU/compleasm