name: cactus
owner: galaxy-australia
long_description: |
  Cactus is a reference-free whole-genome multiple alignment program
categories:
- Sequence Analysis
remote_repository_url: https://github.com/usegalaxy-au/galaxy-local-tools/tree/master/tools/cactus
homepage_url: https://github.com/ComparativeGenomicsToolkit/cactus/
type: unrestricted
auto_tool_repositories:
  name_template: "{{ tool_id }}"
  description_template: "{{ tool_name }} tool from the cactus suite"
suite:
  name: suite_cactus
  description: 
  long_description: |
    Cactus is a reference-free whole-genome multiple alignment program