categories: [Sequence Analysis]
description: Sinto single-cell analysis tools
homepage_url: https://github.com/timoast/sinto
long_description: Sinto is a toolkit for processing aligned single-cell data. Used to add cell barcodes 
  to FASTQ read names and create a scATAC-seq fragments file from a BAM file.
name: sinto
owner: iuc
