name: smallgenomeutilities
owner: iuc
description: Set of utilities for manipulating small viral genome data.
long_description: |
  The smallgenomeutilities are a collection of scripts that is useful
  for dealing and manipulating NGS data of small viral genomes.
  They are written in Python 3 with a small number of dependencies.
  Developed as part of the `V-pipe workflow for analysing NGS data of short viral genomes <https://github.com/cbg-ethz/V-pipe>`_.
categories:
- Sequence Analysis
remote_repository_url: https://github.com/galaxyproject/tools-iuc/tree/master/tools/smallgenomeutilities
homepage_url: https://github.com/cbg-ethz/smallgenomeutilities
type: unrestricted
