name: genrich
owner: iuc
description: |
  Genrich is a peak-caller for genomic enrichment assays (e.g. ChIP-seq, ATAC-seq). 
homepage_url: https://github.com/jsh58/Genrich
long_description: |
  Genrich is a peak-caller for genomic enrichment assays (e.g. ChIP-seq, ATAC-seq). 
  It analyzes alignment files generated following the assay and produces a file detailing peaks of significant enrichment.
auto_tool_repositories:
  name_template: "{{ tool_id }}"
  description_template: "{{ tool_name }} tool from the meme package"
remote_repository_url: https://github.com/jsh58/Genrich
type: unrestricted
categories:
  - ChIP-seq
