categories:
- Metabolomics
description: DIMet is a bioinformatics pipeline for differential analysis of isotopic targeted labeling data.
homepage_url: https://github.com/cbib/DIMet
long_description: .
owner: iuc
remote_repository_url: https://github.com/galaxyproject/tools-iuc/tree/master/tools/DIMet
type: unrestricted
auto_tool_repositories:
  name_template: "{{ tool_id }}"
  description_template: "Wrapper for DIMet application {{ tool_name }}."
suite:
  name: "suite_dimet"
  description: "A suite of Galaxy tools designed to work with version 1.9 of the bcftools package."
  type: repository_suite_definition