categories:
- Metabolomics
description: DIMet is a bioinformatics pipeline for differential analysis of isotopic targeted labeling data.
homepage_url: https://github.com/cbib/DIMet
long_description:
  Visit our Galaxy modules:
    abundance_plot : https://usegalaxy.eu/?tool_id=toolshed.g2.bx.psu.edu%2Frepos%2Fiuc%2Fdimet_abundance_plot%2Fdimet_abundance_plot%2F0.1.4%2Bgalaxy0&version=latest
    differential_analysis: https://usegalaxy.eu/?tool_id=toolshed.g2.bx.psu.edu%2Frepos%2Fiuc%2Fdimet_differential_analysis%2Fdimet_differential_analysis%2F0.1.4%2Bgalaxy0&version=latest
owner: iuc
remote_repository_url: https://github.com/galaxyproject/tools-iuc/tree/master/tools/DIMet
type: unrestricted
auto_tool_repositories:
  name_template: "{{ tool_id }}"
  description_template: "Wrapper for DIMet application {{ tool_name }}."
suite:
  name: "suite_dimet"
  description: "DIMet is a bioinformatics pipeline for differential analysis of isotopic targeted labeling data"
  type: repository_suite_definition