description: HH-suite3 for sensitive sequence searching
long_description: The HH-suite is an open-source software package for sensitive protein sequence searching based on the pairwise alignment of hidden Markov models (HMMs).
homepage_url: https://github.com/soedinglab/hh-suite
name: hhsuite
owner: guerler
type: unrestricted
categories:
 - Sequence Analysis
auto_tool_repositories:
  name_template: "{{ tool_id }}"
  description_template: "HHsuite: {{ tool_name }}."
suite:
  name: "suite_hhsuite"
  description: "A suite of tools designed to identify distantly related sequence homologues"
  type: repository_suite_definition
