owner: iuc
categories:
  - CNVkit
suite:
  name: suite_cnvkit
  description: "A suite of Galaxy tools designed to work with the cnvkit python library."
  long_description: |
    CNVkit is a Python library and command-line software toolkit to infer and visualize
    copy number from high-throughput DNA sequencing data. It is designed for use with hybrid
    capture, including both whole-exome and custom target panels, and short-read sequencing platforms
    such as Illumina and Ion Torrent.
  include_repositories:
  - name: cnvkit_access
    owner: iuc
  - name: cnvkit_antitarget
    owner: iuc
  - name: cnvkit_autobin
    owner: iuc
  - name: cnvkit_batch
    owner: iuc
  - name: cnvkit_call
    owner: iuc
  - name: cnvkit_coverage
    owner: iuc
  - name: cnvkit_diagram
    owner: iuc
  - name: cnvkit_fix
    owner: iuc
  - name: cnvkit_heatmap
    owner: iuc
  - name: cnvkit_reference
    owner: iuc
  - name: cnvkit_scatter
    owner: iuc
  - name: cnvkit_segment
    owner: iuc
  - name: cnvkit_target
    owner: iuc