categories:
- Sequence Analysis
description: Fast local alignment boundaries
name: mashmap
owner: iuc
remote_repository_url: https://github.com/galaxyproject/tools-iuc/tree/master/tools/mashmap
synopsis: optimised for long reds
type: unrestricted
