label: differential-analysis-example

defaults:
  - dataset: example2_data
  - method: differential_analysis

#comparisons :
#  - [[L-Cycloserine, T0], [Control, T0]]
#  - [[L-Cycloserine, T2h], [Control, T2h]]

#statistical_test:
#  abundances: prm-scipy
#  mean_enrichment: ranksum
#  isotopologue_proportions: disfit


