label: distribution-fitting-plot-example

defaults:
  - dataset: example2_data
  - method: distr_fit_plot

comparisons :
  - [[L-Cycloserine, T0], [Control, T0]]
  - [[L-Cycloserine, T2h], [Control, T2h]]

statistical_test:
  isotopologue_proportions: disfit

  


