label: isotopologues-stacked-for-example2-data
# Abundances bars configuration
# -----------------------------

defaults:
  - dataset: example2_data
  - method: mean_enrichment_line_plot

#width_subplot : !!float 4


