label: isotopologues-stacked-for-example2-data
# Abundances bars configuration
# -----------------------------

defaults:
  - dataset: example2_data
  - method: isotopologue_proportions_plot

#timepoints:
#  - T0
#  - T2h

# width_each_stack: !!float 3.9
# inner_numbers_size : !!float 13.5


