label: metabologram-example4

defaults:
  - dataset: example4_data_metabologram
  - method: metabologram_integration
  
#comparisons :
#  - [[L-Cycloserine, T0], [Control, T0]]
#  - [[L-Cycloserine, T2h], [Control, T2h]]
#

statistical_test: # metabologram only admits one: abundances OR mean_enrichment
  abundances: ranksum


compartment : cell #  metabologram only admits one compartment

columns_metabolites: 
  ID: metabolite
  values : log2FC  # Log2FC|FC
  
columns_transcripts:
  ID : external_gene_name
  values : log2FoldChange
  





