label: multi-group-comparison-example3

defaults:
  - dataset: example3_data
  - method: multi_group_comparison

#conditions:
#  - [Control, T0h]
#  - [Control, T2h]
#  - [Cond1, T0h]
#  - [Cond2, T2h]

datatypes:
  - abundances
