label: time_course_analysis_example

defaults:
  - dataset: example2_data
  - method: time_course_analysis
 
  
#statistical_test:
#  abundances: prm-scipy
#  mean_enrichment: ranksum
#  isotopologue_proportions: ranksum


