categories: [Sequence Analysis]
description: "Compleasm: a faster and more accurate reimplementation of BUSCO"
homepage_url: https://github.com/huangnengCSU/compleasm
name: compleasm
owner: iuc
remote_repository_url: https://github.com/galaxyproject/tools-iuc/tree/master/tools/compleasm/