hydra:
  job:
    name: multi_group_comparison
  run:
    dir: outputs/${analysis.dataset.label}-${analysis.method.label}

# check https://hydra.cc/docs/patterns/specializing_config/ for more info about this
defaults:
  - analysis: multi_group_comparison_example

figure_path: figures
table_path: tables


