hydra:
  job:
    name: pca_plot
  run:
    dir: output/${analysis.dataset.label}-${analysis.method.label}

# check https://hydra.cc/docs/patterns/specializing_config/ for more info about this
defaults:
  - _self_
  - analysis: pca_plot_example

figure_path: figures
table_path: tables


