hydra:
  job:
    name: enrichment_lineplot
  run:
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}/${analysis.dataset.label}-${analysis.method.label}

# check https://hydra.cc/docs/patterns/specializing_config/ for more info about this
defaults:
  - analysis: enrich_lineplot_example

figure_path: figures
table_path: tables



#palette: pastel # TODO : vverify, only used in abundance bars? or also in lineplots? 
#x_text: ''  # TODO : x_text param is only used in abundance bars, move there
