hydra:
  job:
    name: abundance_plot_dimet_galaxy
  run:
    dir: outputs/${analysis.dataset.label}-${analysis.method.label}

# check https://hydra.cc/docs/patterns/specializing_config/ for more info about this
defaults:
  - analysis: abundance_plot_example

figure_path: figures
table_path : tables


