hydra:
  job:
    name: distribution_fit_plot
  run:
    dir: outputs/${analysis.dataset.label}-${analysis.method.label}

# check https://hydra.cc/docs/patterns/specializing_config/ for more info about this
defaults:
  - analysis: distrfit_plot_example

figure_path: figures
table_path: tables


