# YOU NEED THIS 
# indicate that we want an instance of Dataset created for this config
_target_: data.DatasetConfig

#label: example3
name: I am a sythetic data example
#subfolder: example3_data

# ALWAYS WITHIN THE RAW SUBFOLDER
#metadata: example3_metadata
#abundances: rawAbundances
#
#conditions :
# - Control
# - Cond1
# - Cond2
 


