# YOU NEED THIS 
# indicate that we want an instance of DataIntegration created for this config
_target_: data.DataIntegrationConfig

label: example4
name: I am a sythetic data example
#subfolder: example4_data

#conditions :
# - Control # first must be control
# - L-Cycloserine

# ALWAYS WITHIN THE RAW SUBFOLDER
#metadata: example2_metadata
#abundances: rawAbundances
#mean_enrichment: FracContribution_C
  
# ALWAYS IN INTEGRATION_FILES SUBFOLDER
#transcripts:  # same order as your metabolomics comparisons in analysis config
#  - DEG_comparison_1
#  - DEG_comparison_2

pathways: 
  metabolites: pathways_kegg_metabolites
  transcripts: pathways_kegg_transcripts




