# YOU NEED THIS 
# indicate that we want an instance of Dataset created for this config
_target_: data.DatasetConfig

#label: example1
name: I am a sythetic data example
#subfolder: example1_data

# ALWAYS WITHIN THE RAW SUBFOLDER
#metadata: example1_metadata
#abundances: AbundanceCorrected
#
#conditions :
# - sgLDHA # first must be control

