# YOU NEED THIS 
# indicate that we want an instance of Dataset created for this config
_target_: data.DatasetConfig

#label: example2
name: I am a synthetic data example
#subfolder: example2_data

# ALWAYS WITHIN THE RAW SUBFOLDER
# metadata: example2_metadata
# abundances: rawAbundances
# mean_enrichment: FracContribution_C
# isotopologue_proportions: CorrectedIsotopologues # isotopologue proportions


#conditions :
# - Control # first must be control
# - L-Cycloserine


