categories:
- CNVkit
name: cnvkit_heatmap
owner: iuc
remote_repository_url: "https://github.com/galaxyproject/tools-iuc/tree/master/tools/cnvkit/cnvkit_heatmap"
homepage_url: "https://github.com/etal/cnvkit"
long_description: |
  CNVkit is a Python library and command-line software toolkit to infer and visualize copy number from high-throughput DNA sequencing data. It is designed for use with hybrid capture, including both whole-exome and custom target panels, and short-read sequencing platforms such as Illumina and Ion Torrent.
categories:
- "Variant Analysis"
auto_tool_repositories:
  name_template: "{{ tool_id }}"
  description_template: "Wrapper for {{ tool_name }}"
