description: Creates ffindex/ffdata database files from individual files
long_description: DBKit is capable of downloading individual files from external resources and creating a ffindex/ffdata database file pair. Database file pairs can also be constructed from collections. Additionally this package contains tools to extract and merge database files.
homepage_url: https://github.com/guerler/springsuite
name: ffindex-dbkit
owner: guerler
type: unrestricted
categories:
 - Sequence Analysis
auto_tool_repositories:
  name_template: "{{ tool_id }}"
  description_template: "DBKit: {{ tool_name }}."
suite:
  name: "suite_ffindex_dbkit"
  description: "A suite of tools to generate ffindex/ffdata pairs"
  type: repository_suite_definition
