categories: 
- Variant Analysis
description: cnv-phenopacket Converts TSV metadata file to JSON.
long_description: cnv-phenopacket is a pyhton tool that Converts TSV metadata file to JSON.
homepage_url: https://pypi.org/project/cnv-phenopacket/
name: cnv-phenopacket
owner: iuc
remote_repository_url: https://pypi.org/project/cnv-phenopacket/
auto_tool_repositories:
  name_template: "{{ tool_id }}"
  description_template: "Wrapper for {{ tool_name }}."
